### PR TITLE
Adding linux package support

### PR DESCRIPTION
**Pull request by hbiel**
Hi everyone!

I'm using homebrew to bootstrap my linux enviroment and noticed your tool only supports macOS.
I have found a quick solution on similar formulae and applied that here.

Would that be something you could incorporate and maintain going forward?

Best regards!

### CODE REVIEW

**Comment by simonharrer** [comment]
Great idea. 

In the repository of the mob tool theres a github action in the release train that automatically creates a PR for every new version. See https://github.com/remotemobprogramming/mob/blob/885d0f209248531e1b84841edf6ced5b2e04356b/.github/workflows/release.yaml#L47

We need to think on how to automate this for both macos and linux. I only would like to merge this PR when we have a solution for the automation of the releases.

**Comment by hbiel** [comment]
Absolutely! Thank's for pointing me to your GitHub Actions.

I don't know if my proposed solution is a more common or even recommended one. To me the most feasible solution for automating this seems to be using a template of the formula file with the relevant details being placeholders (eg. version, revision, url_darwin, sha256_darwin, url_linux, sha256_linux, etc.). The interpolated file could then be created as a PR for this repo. 

Does this seem like a good solution for you?

The official way seems to be using 'bottles' instead from what I've gathered. But I don't really know what that entails and how this works exactly. I suppose it's a bigger change all around.

Let me know what you think about this.

**Comment by simonharrer** [comment]
Perhaps this bottle thing might also be something we need to investigate. With macOS m1 chips getting more popular I‘d like to ship an arm64 binary as well. Templates would work in both cases. I, however, like the simplicity of the current brew commands I can use to create the pull requests for updating… so I’m not sure which is the best way without more info.

**Comment by hbiel** [comment]
> Perhaps this bottle thing might also be something we need to investigate. With macOS m1 chips getting more popular I‘d like to ship an arm64 binary as well. 

I think investigating the bottle mechanism would be a good idea then. I skimmed through it a little bit but did not get my head around it fully so far.

These are my findings:

On this Page they are saying the following:
https://docs.brew.sh/Formula-Cookbook#updating-formulae

`Leave the bottle do ... end block as-is; our CI system will update it when we pull your change.`

I guess this applies when the formula lies in the homebrew_core repository. Maybe that's interesting for you too.

So I guess if this is the case, you could just create the bottle block once and from there on you would only need to update the version information as you do now.

This is just my understanding from what I've gathered so far. So take this with a grain of salt.

> Templates would work in both cases. I, however, like the simplicity of the current brew commands I can use to create the pull requests for updating…

I agree and it should be kept as simple as possible.

> so I’m not sure which is the best way without more info.

Regarding homebrew I think it would be best to stick to their solution. And in this case it seems to be creating bottles for different architectures.

I just can't say for sure what that entails for the rest of your build pipeline.

Honestly I don't know if I will find the time to dive deeper into this at the moment. So I think this PR can be closed for now.

**Pull request closed without merging**
